### ISSUE TITLE
ESLint warnings passes lint-staged check

### ISSUE THREAD

**Issue by felicio** [strv-academy-2017/frontend-project-starter#8]
Presumably, `lint-staged` module __does not__ strictly enforce `eslint` warnings and allows the code to be committed regardless.

**Comment by prichodko** [comment]
It's not `lint-staged`s fault. The result of `lint-staged` is based upon results of executed commands. Since `eslint` does not return negative result upon warnings (and it shouldn't - only errors, that's why they are warnings), because you don't want some warnings to break your build while deploying, for example.
